### ISSUE TITLE
[BUG] Wrong description and screenshot in Building your first WebContainer app

### ISSUE THREAD

**Issue by morinokami** [stackblitz/webcontainer-docs#12]
**Describe the bug**

In https://webcontainers.io/tutorial/1-building-your-first-webcontainers-app#_2-create-and-style-a-textarea-and-an-iframe, a screenshot is shown with the sentence "Our page now features three boxes", but there are actually two boxes in the page, so I think the description and screenshot should be updated.

**To Reproduce**

1. Go to https://webcontainers.io/tutorial/1-building-your-first-webcontainers-app
2. Just follow the tutorial

**Expected behavior**

Explain that two boxes are displayed and show an appropriate screenshot.

**Screenshots**

Screenshot of the page at this stage on my machine:

<img width="1512" alt="Screen Shot 2023-02-19 at 20 58 27" src="https://user-images.githubusercontent.com/7889778/219947573-fb11ac33-b1b5-4311-841d-59ce67a1c60f.png">

Screenshot of the corresponding section of the tutorial:

<img width="1512" alt="Screen Shot 2023-02-19 at 21 27 19" src="https://user-images.githubusercontent.com/7889778/219947930-09664a38-a3c6-48c9-91c8-b7a89bba16fd.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1 (21G83)
 - Browser: Google Chrome 108.0.5359.94

**Comment by sylwiavargas** [comment]
Thank you - good catch!  We've fixed it now!
